# -*- coding: utf-8 -*-
#+AUTHOR: ifritJP
#+STARTUP: nofold
#+OPTIONS: ^:{}
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="org-mode-document.css" />

#+TITLE: TODO


- [ ] When PRE_ENC is enabled, reconnection communication recovery cannot be performed normally.
   - CryptCtrlObj encrypted with packetEncrypter() and
     Since CryptCtrlObj after resending is a different thing,
     Decryption cannot be performed normally.
     You need to use the same CryptCtrlObj after resending.

- [ ] tunnel console to support inter-terminal chat
- [ ] Allow to open console after authentication
- After setting [ ] tunnel, if you timeout without starting a session,
       Error trying to listen on port in use
- [ ] Don't exit when dst fails to connect
- [ ] Create a control console
- [ ] Prepare a console that allows you to check traffic in real time
- [ ] Set timeout for authentication process.
       - [ ] After authentication processing, set the timeout considering the value of interval
- [ ] Add timeout to reconnect
- [ ] Stop connection when signal is received

- [X] Reject connection request with non-existing sessionId
- [X] On close, print the number of packets and also the number of combined packets
- [X] Allow client to specify dst host.
       - [X] Make it possible to fix it on the server side.
-[X] Between receiving the packet and sending her SYNC,
       If the other party is sending packets up to the limit MAX,
       Her SYNC sent by the other party cannot be received.
-[X] Only her NORMAL is resent.
       A contradiction occurs if the other packets are not resent as well.
       In particular, if he doesn't resend the SYNC, the synchronization control will collapse and it won't work.
- Can't stop when waiting for [X] channel.
- [X] Ignore dummy packets during reconnect
- [X] Limit number of simultaneous negotiations
- [X] Log negotiation progress
-[X] When reconnecting, he can end up with EOF without retrying.
- [X] specify the host port of dst on the command line
- [X] Check the number of sessions for each source IP, and if the number of sessions exceeds the default value,
       get authentication error
       Do this at the same time as confirming the IP.
- [X] Create a mode to measure communication speed